### PR TITLE
Add metrics folder and MMD implementation 

### PR DESCRIPTION
**Pull request by Justin-Yuan**
Other metrics can be implemented as modules under `safe_control_gym/math_and_models/common_metrics/` , or if suitable under the existing `similarity_metrics.py`. 

An issue is if there's currently a `metrics.py` file under `math_and_models` with the CVaR robustness metric computation, used in `experiment.py`, it would be better to put it under the `common_metrics/` folder as well and rename the folder to `metrics/`.

### CODE REVIEW

**Comment by melissagreeff204** [comment]
I don't see any issues except that there will have to be an additional PR later to move CVaR robustness metric computation into /common_metrics and delete the current metrics.py and update experiment.py. Is this possible to do now?

**Comment by Justin-Yuan** [comment]
@melissagreeff204 I updated/rearranged the metrics files in this PR accordingly, now all metrics are under `safe_control_gym/math_and_models/metrics/`

**Comment by melissagreeff204** [comment]
Looks good to me.

**Comment by Justin-Yuan** [comment]
@JacopoPan can I merge it? there should be no conflicts with other files and other PRs waiting in line.  Then melissa and I can start adding similarity metrics for testing.

**Review by JacopoPan — APPROVED** [review]

**Comment by JacopoPan** [comment]
> @JacopoPan can I merge it? there should be no conflicts with other files and other PRs waiting in line. Then melissa and I can start adding similarity metrics for testing.

👍

**Pull request merged**
