### PR TITLE
Add static code analysis workflow

### PR DESCRIPTION
**Pull request by amrit110**
Add static code analysis github actions workflow file
Includes code formatting check using black, flake8 checks and mypy checks

### CODE REVIEW

**Comment by amrit110** [comment]
Hi @JacopoPan , so this PR adds github actions workflow file for static code analysis. If this is merged, github actions should fail for all three checks (black, flake8 and mypy). You can view the jobs being run here (https://github.com/amrit110/safe-control-gym/actions/runs/1806793482). If you feel that the analysis jobs and the respective configs make sense, I can add commits to this PR to fix the respective errors. Note that black code formatting would probably change all python files, and I recommend you to maybe check for an example file to see if the formatting is to your liking.

**Comment by JacopoPan** [comment]
Thank no. 2. Let me just just merge the other PR and port some new code over from a different repo before tackling this one.

**Comment by JacopoPan** [comment]
Just to give you an update on this, I am going through the other PRs (and there's a few that will be created internally from the lab in the next few days). I will only look at static analysis and code re-formatting after all those have been included and tested (ideally just after an upcoming journal/conference submission this month).

**Comment by JacopoPan** [comment]
I'm (temporarily) closing this. We'll review static analysis after more "new content" PRs are merged.

**Pull request closed without merging**
